/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dp_programming;

import dev.ming.Library;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());//kanbudong
        System.out.println("test"); //test 
    }
}
